### ISSUE TITLE
DO NOT INCLUDE CONFIG FILE

### ISSUE THREAD

**Issue by ghost** [mi171344/git-test#3]
r u serious?

**Comment by mi171344** [comment]
No

**Comment by mi171333** [comment]
uh oh

**Comment by mi171344** [comment]
kuso ripu yamete kudasai !!

**Comment by ghost** [comment]
no way

**Comment by mi171335** [comment]
こちらが　濃厚とんこつ豚無双さんの
濃厚無双ラーメン　海苔トッピングです
うっひょ～～～～～～！
着席時　コップに水垢が付いていたのを見て
大きな声を出したら　店主さんからの誠意で
チャーシューをサービスしてもらいました
俺の動画次第でこの店潰すことだって出来るんだぞってことで
いただきま～～～～す！まずはスープから
コラ～！
これでもかって位ドロドロの濃厚スープの中には
虫が入っており　怒りのあまり
卓上調味料を全部倒してしまいました～！
すっかり店側も立場を弁え　誠意のチャーシュー丼を貰った所で
お次に　圧倒的存在感の極太麺を
啜る～！　殺すぞ～！
ワシワシとした触感の麺の中には、髪の毛が入っており
さすがのSUSURUも　厨房に入って行ってしまいました～！
ちなみに、店主さんが土下座している様子は　ぜひサブチャンネルを御覧ください

**Comment by ghost** [comment]
<><

**Comment by mi171344** [comment]
もう卒業後のチャットツールはgithubのissueだな！！

**Comment by mi171333** [comment]
SUSURU TV!?!?

**Comment by mi171333** [comment]
uh

**Comment by mi171344** [comment]
これ先生が見たら面白いな

**Comment by mi171333** [comment]
github規制されちゃうぜ

**Comment by mi171338** [comment]
@mi171304 Hi!

**Comment by mi171335** [comment]
こちらが　濃厚とんこつ豚無双さんの
濃厚無双ラーメン　海苔トッピングです

# **うっひょ～～～～～～！**

着席時　コップに水垢が付いていたのを見て
大きな声を出したら　店主さんからの誠意で
チャーシューをサービスしてもらいました
俺の動画次第でこの店潰すことだって出来るんだぞってことで
いただきま～～～～す！まずはスープから
# コラ～！
これでもかって位ドロドロの濃厚スープの中には
虫が入っており　怒りのあまり
卓上調味料を全部倒してしまいました～！
すっかり店側も立場を弁え　誠意のチャーシュー丼を貰った所で
お次に　圧倒的存在感の極太麺を
## 啜る～！
# 殺すぞ～！
ワシワシとした触感の麺の中には、髪の毛が入っており
さすがのSUSURUも　厨房に入って行ってしまいました～！
###### ちなみに、店主さんが土下座している様子は　ぜひサブチャンネルを御覧ください

**Comment by mi171338** [comment]
- [ ] だめ
- [x] いい
- [ ] よくない
- [x] よい

**Comment by ghost** [comment]
I can't believe what you done
